//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Console.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_TAB_POPUP_MENU              129

#define IDPANE_CAPS_INDICATOR           130
#define IDPANE_NUM_INDICATOR            131
#define IDPANE_SCRL_INDICATOR           132
#define IDPANE_PID_INDICATOR            133
#define IDPANE_SELECTION                134
#define IDPANE_COLUMNS_ROWS             135
#define IDPANE_BUF_COLUMNS_ROWS         136
#define IDPANE_ZOOM                     137

#define IDD_RENAME_TAB                  204
#define IDD_SETTINGS_MAIN               205
#define IDD_SETTINGS_CONSOLE            206
#define IDD_SETTINGS_APPEARANCE         207
#define IDD_SETTINGS_HOTKEYS            208
#define IDD_SETTINGS_TRANSPARENCY       209
#define IDD_SETTINGS_STYLES             210
#define IDD_SETTINGS_TABS               211
#define IDD_SETTINGS_BEHAVIOR           212
#define IDD_SETTINGS_TABS_1             213
#define IDD_SETTINGS_TABS_2             214
#define IDD_SETTINGS_MOUSE              215
#define IDD_CREDENTIALS                 216
#define IDD_SETTINGS_FULLSCREEN         217
#define IDD_SETTINGS_TABS_COLORS        218
#define IDD_SETTINGS_FONT               219
#define IDD_SETTINGS_BEHAVIOR_2         220
#define IDD_SETTINGS_TABS_ENV           221

#define IDR_TOOLBAR_16                  300
#define IDR_FULLSCREEN1_16              301
#define IDR_FULLSCREEN2_16              302
#define IDR_SEARCH_16                   303

#define IDR_TOOLBAR_20                  310
#define IDR_FULLSCREEN1_20              311
#define IDR_FULLSCREEN2_20              312
#define IDR_SEARCH_20                   313

#define IDR_TOOLBAR_24                  320
#define IDR_FULLSCREEN1_24              321
#define IDR_FULLSCREEN2_24              322
#define IDR_SEARCH_24                   323

#define IDR_TOOLBAR_32                  330
#define IDR_FULLSCREEN1_32              331
#define IDR_FULLSCREEN2_32              332
#define IDR_SEARCH_32                   333

#define IDC_TAB_NAME                    1000
#define IDC_APPLY                       1001
#define IDC_TREE_SECTIONS               1002
#define IDC_CHILD_PLACEHOLDER           1003
#define IDC_CHANGE_REFRESH              1005
#define IDC_REFRESH                     1006
#define IDC_ROWS                        1007
#define IDC_COLUMNS                     1008
#define IDC_BUFFER_ROWS                 1010
#define IDC_BUFFER_COLUMNS              1011
#define IDC_SHELL                       1012
#define IDC_INIT_DIR                    1013
#define IDC_BTN_BROWSE_SHELL            1015
#define IDC_BTN_BROWSE_DIR              1016
#define IDC_BTN_BROWSE_BK               1017
#define IDC_CLR_00                      1017
#define IDC_CLR_01                      1018
#define IDC_CLR_02                      1019
#define IDC_CLR_03                      1020
#define IDC_CLR_04                      1021
#define IDC_CLR_05                      1022
#define IDC_CLR_06                      1023
#define IDC_CLR_07                      1024
#define IDC_CLR_08                      1025
#define IDC_CLR_09                      1026
#define IDC_CLR_10                      1027
#define IDC_CLR_11                      1028
#define IDC_CLR_12                      1029
#define IDC_CLR_13                      1030
#define IDC_CLR_14                      1031
#define IDC_CLR_15                      1032
#define IDC_DEF_00                      1033
#define IDC_DEF_01                      1034
#define IDC_DEF_02                      1035
#define IDC_DEF_03                      1036
#define IDC_DEF_04                      1037
#define IDC_DEF_05                      1038
#define IDC_DEF_06                      1039
#define IDC_DEF_07                      1040
#define IDC_DEF_08                      1041
#define IDC_DEF_09                      1042
#define IDC_DEF_10                      1043
#define IDC_DEF_11                      1044
#define IDC_DEF_12                      1045
#define IDC_DEF_13                      1046
#define IDC_DEF_14                      1047
#define IDC_DEF_15                      1048
#define IDC_FONT                        1049
#define IDC_BTN_BROWSE_FONT             1050
#define IDC_FONT_SIZE                   1051
#define IDC_SPIN_FONT_SIZE              1052
#define IDC_CHECK_BOLD                  1053
#define IDC_CHECK_ITALIC                1054
#define IDC_ACTIVE_ALPHA                1055
#define IDC_SPIN_INSIDE_BORDER          1056
#define IDC_INACTIVE_ALPHA              1057
#define IDC_SPIN_CHANGE_REFRESH         1058
#define IDC_SPIN_REFRESH                1059
#define IDC_BTN_BROWSE_ICON             1060
#define IDC_SPIN_ROWS                   1061
#define IDC_SPIN_BUFFER_ROWS            1062
#define IDC_SPIN_COLUMNS                1063
#define IDC_SPIN_BUFFER_COLUMNS         1064
#define IDC_BTN_RESET_COLORS            1065
#define IDC_STATIC_ACTIVE_ALPHA         1066
#define IDC_STATIC_INACTIVE_ALPHA       1067
#define IDC_TRANSPARENCY_TYPE           1068
#define IDC_TRANSPARENCY_TYPE2          1069
#define IDC_TRANSPARENCY_TYPE3          1070
#define IDC_TRANSPARENCY_TYPE4          1071
#define IDC_TRANSPARENCY_TYPE5          1072
#define IDC_STATIC_ACTIVE_WINDOW        1073
#define IDC_STATIC_INACTIVE_WINDOW      1074
#define IDC_STATIC_KEY_COLOR            1075
#define IDC_LIST_HOTKEYS                1076
#define IDC_BTN_ASSIGN                  1077
#define IDC_EDIT_HOTKEY                 1078
#define IDC_EDIT_COMMAND                1079
#define IDC_SELECTION_COLOR             1079
#define IDC_BTN_CLEAR                   1080
#define IDC_FONT_COLOR                  1081
#define IDC_CHECK_USE_COLOR             1082
#define IDC_CHECK_SHOW_MENU             1083
#define IDC_CHECK_SHOW_TOOLBAR          1084
#define IDC_CHECK_SHOW_STATUS           1085
#define IDC_CHECK_SHOW_TABS             1086
#define IDC_CHECK_STYLE_CAPTION         1087
#define IDC_CHECK_STYLE_RESIZABLE       1088
#define IDC_CHECK_STYLE_TASKBAR         1089
#define IDC_CHECK_STYLE_BORDER          1090
#define IDC_INSIDE_BORDER               1091
#define IDC_POS_X                       1092
#define IDC_CHECK_HIDE_SINGLE_TAB       1092
#define IDC_CHECK_STYLE_TRAY            1093
#define IDC_POS_Y                       1094
#define IDC_CHECK_SHOW_SCROLLBARS       1094
#define IDC_CHECK_STYLE_QUAKE           1096
#define IDC_CHECK_USE_JUMPLIST          1097
#define IDC_CHECK_RTF                   1098
#define IDC_KEY_COLOR                   1099
#define IDC_TRIM_TAB_TITLES             1101
#define IDC_TRIM_TAB_TITLES_RIGHT       1102
#define IDC_SNAP                        1104
#define IDC_CHECK_POSITION              1105
#define IDC_CHECK_SNAP                  1106
#define IDC_SPIN_X                      1107
#define IDC_SPIN_Y                      1108
#define IDC_SPIN_SNAP                   1109
#define IDC_WINDOW_TITLE                1110
#define IDC_WINDOW_ICON                 1111
#define IDC_CHECK_USE_TAB_TITLE         1112
#define IDC_CHECK_USE_TAB_ICON          1113
#define IDC_MAIN_TITLE_FORMAT           1114
#define IDC_TAB_TITLE_FORMAT            1115
#define IDC_LIST_TABS                   1116
#define IDC_SPIN_TRIM_TAB_TITLES        1116
#define IDC_TAB_TITLE                   1117
#define IDC_SPIN_TRIM_TAB_TITLES_RIGHT  1117
#define IDC_TAB_ICON                    1118
#define IDC_TAB_SHELL                   1119
#define IDC_TAB_INIT_DIR                1120
#define IDC_COMBO_CURSOR                1121
#define IDC_CURSOR_COLOR                1122
#define IDC_RADIO_BK_TYPE               1123
#define IDC_CURSOR_ANIM                 1123
#define IDC_RADIO_BK_TYPE2              1124
#define IDC_RADIO_BK_TYPE3              1125
#define IDC_BK_COLOR                    1126
#define IDC_BK_IMAGE                    1127
#define IDC_CHECK_BK_RELATIVE           1128
#define IDC_CHECK_BK_EXTEND             1129
#define IDC_COMBO_BK_POS                1130
#define IDC_TINT_COLOR                  1131
#define IDC_TINT_OPACITY                1132
#define IDC_STATIC_TINT_OPACITY         1133
#define IDC_BTN_ADD                     1134
#define IDC_BTN_UP                      1135
#define IDC_BTN_DOWN                    1136
#define IDC_BTN_DELETE                  1137
#define IDC_STATIC_BK_COLOR             1138
#define IDC_BTN_CLONE                   1138
#define IDC_STATIC_TINT_COLOR           1139
#define IDC_STATIC_BK_IMAGE             1140
#define IDC_STATIC_BK_POS               1141
#define IDC_TINT_OPACITY_VAL            1142
#define IDC_CHECK_COPY_ON_SELECT        1143
#define IDC_CHECK_NO_WRAP               1144
#define IDC_CHECK_TRIM_SPACES           1145
#define IDC_CHECK_DRAG_ON               1146
#define IDC_TABS                        1146
#define IDC_CHECK_CLEAR_ON_COPY         1146
#define IDC_CHECK_INVERSE_SHIFT         1147
#define IDC_CHECK_SENSITIVE_COPY        1147
#define IDC_CHECK_TRIM_TAB_TITLES       1148
#define IDC_STATIC_TRIM_CHARS           1149
#define IDC_STATIC_TRIM_CHARS2          1150
#define IDC_STATIC_TRIM_CHARS3          1151
#define IDC_PAGE_SCROLL                 1150
#define IDC_PAGE_SCROLL2                1151
#define IDC_SCROLL_PAGE_ROWS            1152
#define IDC_SPIN_SCROLL_PAGE_ROWS       1153
#define IDC_STATIC_ROWS                 1154
#define IDC_STATIC_VERSION              1155
#define IDC_TAB_FLASHES                 1155
#define IDC_CHECK_SAVE_POSITION         1156
#define IDC_SPIN_TAB_FLASHES            1156
#define IDC_CHECK_SAVE_SIZE             1157
#define IDC_CHECK_USE_SCROLL_LOCK       1158
#define IDC_CHECK_BOLD_INTENSIFIED      1158
#define IDC_CHECK_ITALIC_INTENSIFIED    1159
#define IDC_LIST_MOUSE_COMMANDS         1160
#define IDC_COMBO_BUTTONS               1161
#define IDC_CHECK_CTRL                  1162
#define IDC_CHECK_SHIFT                 1163
#define IDC_CHECK_USER_DATA_DIR         1163
#define IDC_CHECK_ALT                   1164
#define IDC_RADIO_COPY_NEWLINE_CHAR     1164
#define IDC_RADIO2                      1165
#define IDC_COMBO_DOCKING               1167
#define IDC_COMBO_ZORDER                1168
#define IDC_CHECK_FLASH_TAB             1168
#define IDC_COMBO_SMOOTHING             1169
#define IDC_CHECK_LEAVE_HIGHLIGHTED     1170
#define IDC_CHECK_START_HIDDEN          1171
#define IDC_CHECK_DEFAULT_ICON          1172
#define IDC_CHECK_TABS_ON_BOTTOM        1173
#define IDC_TAB_USER                    1174
#define IDC_USER                        1175
#define IDC_PASSWORD                    1176
#define IDC_STATIC_TRIM_CHARS_RIGHT     1176
#define IDC_CHECK_RUN_AS_USER           1177
#define IDC_APPTEXT                     1177
#define IDC_STATIC_USER                 1177
#define IDC_APPICON                     1178
#define IDC_STATIC_PASSWORD             1178
#define IDC_BGTEXT_OPACITY              1179
#define IDC_BGTEXT_OPACITY_VAL          1180
#define IDC_STATIC_BGTEXT_OPACITY       1181
#define IDC_CHECK_NET_ONLY              1182
#define IDC_CHECK_START_IN_FULLSCREEN   1183
#define IDC_COMBO_FULLSCREEN_MONITOR    1184
#define IDC_LEFT_DELIMITERS             1185
#define IDC_CHECK_INC_LEFT_DELIMITER    1186
#define IDC_RIGHT_DELIMITERS            1187
#define IDC_CHECK_INC_RIGHT_DELIMITER   1188
#define IDC_CHECK_CLOSING_LAST_TAB      1189
#define IDC_CHECK_CONFIRM_CLOSE_MULTI   1190
#define IDC_BTN_INHERIT_COLORS          1191
#define IDC_BTN_IMPORT_COLORS           1192
#define IDC_FONT_EXTRAWIDTH             1193
#define IDC_SPIN_FONT_EXTRAWIDTH        1194
#define IDC_CHECK_RUN_AS_ADMIN          1195
#define IDC_CHECK_RUN_AS_CURRENT_USER   1196
#define IDC_CHECK_FOCUS_FOLLOW_MOUSE    1197
#define IDC_CHECK_SIZE                  1198
#define IDC_POS_W                       1199
#define IDC_SPIN_W                      1200
#define IDC_POS_H                       1201
#define IDC_SPIN_H                      1202
#define IDC_CHECK_MULTI_INSTANCES       1203
#define IDC_CHECK_HIDE_TAB_ICONS        1204
#define IDC_EOL_SPACES                  1205
#define IDC_SPIN_EOL_SPACES             1206
#define IDC_STATIC_EOL_SPACES_1         1207
#define IDC_STATIC_EOL_SPACES_2         1208
#define IDC_STATIC_FLASHES              1209
#define IDC_CHECK_INTEGRATED_IME        1210
#define IDC_STATIC_COLOR                1211
#define IDC_CHECK_OPEN_CURRENT_DIR      1212
#define IDC_CHECK_USE_CREDPROV          1213
#define IDC_STATIC_QUAKE_1              1214
#define IDC_STATIC_QUAKE_2              1215
#define IDC_QUAKE_ANIMATION_TIME        1216
#define IDC_SPIN_QUAKE_ANIMATION_TIME   1217
#define IDC_CHECK_SHOW_SEARCH_BAR       1218
#define IDC_HIGHLIGHT_COLOR             1219
#define IDC_BTN_INHERIT_CURSOR          1220
#define IDC_BTN_SET_AS_DEFAULT_COLORS   1221
#define IDC_BTN_SET_AS_DEFAULT_CURSOR   1222
#define IDC_BTN_INHERIT_BACKGROUND      1223
#define IDC_BTN_SET_AS_DEFAULT_BACKGROUND 1224
#define IDC_COMBO_BASE_PRIORITY         1225
#define IDC_LIST_ENV                    1226
#define IDC_BTN_ENV_ADD                 1227
#define IDC_BTN_ENV_DELETE              1228
#define IDC_BTN_ENV_EDIT                1229
#define IDC_ENV_VARIABLE                1230
#define IDC_ENV_VALUE                   1231
#define IDC_CHECK_HIDE_WHEN_INACTIVE    1232
#define IDC_CHECK_LIGATURE              1233
#define IDC_CHECK_CONTROLS_FULLSCREEN   1234

#define ID_NEW_TAB_1                    2000
#define ID_SWITCH_TAB_1                 2100
#define ID_EXTERNAL_COMMAND_1           2200
#define ID_NEXT_TAB                     2900
#define ID_PREV_TAB                     2901
#define ID_RENAME_TAB_OK                2902
#define ID_NEXT_VIEW                    2903
#define ID_PREV_VIEW                    2904
#define ID_CLOSE_VIEW                   2905
#define ID_SPLIT_HORIZ                  2906
#define ID_SPLIT_VERT                   2907
#define ID_GROUP_ALL                    2908
#define ID_UNGROUP_ALL                  2909
#define ID_GROUP_TAB                    2910
#define ID_UNGROUP_TAB                  2911
#define ID_LEFT_VIEW                    2912
#define ID_RIGHT_VIEW                   2913
#define ID_TOP_VIEW                     2914
#define ID_BOTTOM_VIEW                  2915
#define ID_DEC_HORIZ_SIZE               2916
#define ID_INC_HORIZ_SIZE               2917
#define ID_DEC_VERT_SIZE                2918
#define ID_INC_VERT_SIZE                2919
#define ID_CLONE_IN_NEW_TAB             2920
#define ID_ATTACH_CONSOLES              2921
#define ID_DETACH_VIEW                  2922
#define ID_SEARCH_COMBO                 2923
#define ID_SEARCH_PREV                  2924
#define ID_SEARCH_NEXT                  2925
#define ID_SEARCH_MATCH_CASE            2926
#define ID_SEARCH_MATCH_WHOLE_WORD      2927
#define ID_FIND                         2928
#define ID_SHOW_CONTEXT_MENU_1          2929
#define ID_SHOW_CONTEXT_MENU_2          2930
#define ID_SHOW_CONTEXT_MENU_3          2931
#define ID_SWITCH_TRANSPARENCY          2932
#define ID_SEND_CTRL_C                  2933
#define ID_DIAGNOSE                     2934
#define ID_FONT_INFO                    2935
#define ID_PASTE_SELECTION              2936
#define ID_TEXT_SELECTION_LEFT_KEY      2937
#define ID_TEXT_SELECTION_RIGHT_KEY     2938
#define ID_TEXT_SELECTION_TOP_KEY       2939
#define ID_TEXT_SELECTION_BOTTOM_KEY    2940
#define ID_TEXT_SELECTION_HOME_KEY      2941
#define ID_TEXT_SELECTION_END_KEY       2942
#define ID_TEXT_SELECTION_PAGEUP_KEY    2943
#define ID_TEXT_SELECTION_PAGEDOWN_KEY  2944
#define ID_COLUMN_SELECTION_LEFT_KEY    2945
#define ID_COLUMN_SELECTION_RIGHT_KEY   2946
#define ID_COLUMN_SELECTION_TOP_KEY     2947
#define ID_COLUMN_SELECTION_BOTTOM_KEY  2948
#define ID_COLUMN_SELECTION_HOME_KEY    2949
#define ID_COLUMN_SELECTION_END_KEY     2950
#define ID_COLUMN_SELECTION_PAGEUP_KEY  2951
#define ID_COLUMN_SELECTION_PAGEDOWN_KEY 2952

#define IDC_DUMP_BUFFER                 3000

#define IDS_CAPTION_ERROR               4000

#define IDS_ERR_CANT_START_SHELL        5000
#define IDS_ERR_CANT_START_SHELL_AS_USER 5001
#define IDS_ERR_DLL_INJECTION_FAILED    5002
#define IDS_ERR_DLL_HOOK_MISSING        5003
#define IDS_ERR_CREATE_SHARED_OBJECTS_FAILED 5004
#define IDS_ERR_CANT_START_SHELL_AS_ADMIN 5005
#define IDS_ERR_CANT_GET_ELEVATION_TYPE 5006
#define IDS_ERR_TAB_CREATE_FAILED       5007

#define IDS_EDIT_SETTINGS               6000
#define IDS_HELP                        6001
#define IDS_APP_EXIT                    6002
#define IDS_NEW_TAB_1                   6003
#define IDS_NEW_TAB_2                   6004
#define IDS_NEW_TAB_3                   6005
#define IDS_NEW_TAB_4                   6006
#define IDS_NEW_TAB_5                   6007
#define IDS_NEW_TAB_6                   6008
#define IDS_NEW_TAB_7                   6009
#define IDS_NEW_TAB_8                   6010
#define IDS_NEW_TAB_9                   6011
#define IDS_NEW_TAB_10                  6012
#define IDS_NEW_TAB_11                  6013
#define IDS_NEW_TAB_12                  6014
#define IDS_SWITCH_TAB_1                6015
#define IDS_SWITCH_TAB_2                6016
#define IDS_SWITCH_TAB_3                6017
#define IDS_SWITCH_TAB_4                6018
#define IDS_SWITCH_TAB_5                6019
#define IDS_SWITCH_TAB_6                6020
#define IDS_SWITCH_TAB_7                6021
#define IDS_SWITCH_TAB_8                6022
#define IDS_SWITCH_TAB_9                6023
#define IDS_SWITCH_TAB_10               6024
#define IDS_NEXT_TAB                    6025
#define IDS_PREV_TAB                    6026
#define IDS_FILE_CLOSE_TAB              6027
#define IDS_EDIT_RENAME_TAB             6028
#define IDS_NEXT_VIEW                   6029
#define IDS_PREV_VIEW                   6030
#define IDS_LEFT_VIEW                   6031
#define IDS_RIGHT_VIEW                  6032
#define IDS_TOP_VIEW                    6033
#define IDS_BOTTOM_VIEW                 6034
#define IDS_DEC_HORIZ_SIZE              6035
#define IDS_INC_HORIZ_SIZE              6036
#define IDS_DEC_VERT_SIZE               6037
#define IDS_INC_VERT_SIZE               6038
#define IDS_CLOSE_VIEW                  6039
#define IDS_DETACH_VIEW                 6040
#define IDS_ATTACH_CONSOLES             6041
#define IDS_SPLIT_HORIZ                 6042
#define IDS_SPLIT_VERT                  6043
#define IDS_CLONE_IN_NEW_TAB            6044
#define IDS_VIEW_FULLSCREEN             6045
#define IDS_VIEW_ZOOM_100               6046
#define IDS_VIEW_ZOOM_INC               6047
#define IDS_VIEW_ZOOM_DEC               6048
#define IDS_GROUP_ALL                   6049
#define IDS_UNGROUP_ALL                 6050
#define IDS_GROUP_TAB                   6051
#define IDS_UNGROUP_TAB                 6052
#define IDS_EDIT_CLEAR                  6053
#define IDS_EDIT_COPY                   6054
#define IDS_EDIT_SELECT_ALL             6055
#define IDS_EDIT_CLEAR_SELECTION        6056
#define IDS_EDIT_PASTE                  6057
#define IDS_EDIT_STOP_SCROLLING         6058
#define IDS_SCROLL_UP                   6059
#define IDS_SCROLL_DOWN                 6060
#define IDS_SCROLL_PAGE_UP              6061
#define IDS_SCROLL_PAGE_DOWN            6062
#define IDS_SCROLL_LEFT                 6063
#define IDS_SCROLL_RIGHT                6064
#define IDS_SCROLL_PAGE_LEFT            6065
#define IDS_SCROLL_PAGE_RIGHT           6066
#define IDS_FIND                        6067
#define IDS_SEARCH_NEXT                 6068
#define IDS_SEARCH_PREV                 6069
#define IDS_SWITCH_TRANSPARENCY         6070
#define IDS_DUMP_BUFFER                 6071
#define IDS_SHOW_CONTEXT_MENU_1         6072
#define IDS_SHOW_CONTEXT_MENU_2         6073
#define IDS_SHOW_CONTEXT_MENU_3         6074
#define IDS_SEND_CTRL_C                 6075
#define IDS_EXTERNAL_COMMAND_1          6076
#define IDS_EXTERNAL_COMMAND_2          6077
#define IDS_EXTERNAL_COMMAND_3          6078
#define IDS_EXTERNAL_COMMAND_4          6079
#define IDS_EXTERNAL_COMMAND_5          6080
#define IDS_EXTERNAL_COMMAND_6          6081
#define IDS_EXTERNAL_COMMAND_7          6082
#define IDS_EXTERNAL_COMMAND_8          6083
#define IDS_EXTERNAL_COMMAND_9          6084
#define IDS_EXTERNAL_COMMAND_10         6085
#define IDS_GLOBAL_ACTIVATE             6086
#define IDS_PASTE_SELECTION             6087

#define IDS_MOUSE_COPY                  7000
#define IDS_MOUSE_SELECT                7001
#define IDS_MOUSE_COLUMNSELECT          7002
#define IDS_MOUSE_PASTE                 7003
#define IDS_MOUSE_DRAG                  7004
#define IDS_MOUSE_LINK                  7005
#define IDS_MOUSE_MENU1                 7006
#define IDS_MOUSE_MENU2                 7007
#define IDS_MOUSE_MENU3                 7008

#define IDS_SETTINGS_CONSOLE            8000
#define IDS_SETTINGS_APPEARANCE         8001
#define IDS_SETTINGS_STYLES             8002
#define IDS_SETTINGS_TRANSPARENCY       8003
#define IDS_SETTINGS_FONT               8004
#define IDS_SETTINGS_FULLSCREEN         8005
#define IDS_SETTINGS_BEHAVIOR           8006
#define IDS_SETTINGS_MORE               8007
#define IDS_SETTINGS_HOTKEYS            8008
#define IDS_SETTINGS_MOUSE              8009
#define IDS_SETTINGS_TABS               8010
#define IDS_SETTINGS_COMMAND            8011
#define IDS_SETTINGS_MOUSE_ACTION       8012
#define IDS_SETTINGS_TAB_NAME           8013
#define IDS_SETTINGS_MAIN               8014
#define IDS_SETTINGS_BACKGROUND         8015
#define IDS_SETTINGS_COLORS_CURSOR      8016
#define IDS_SETTINGS_ENVIRONMENT        8017
#define IDS_SETTINGS_HOTKEY             8018
#define IDS_SETTINGS_VARIABLE           8019
#define IDS_SETTINGS_VALUE              8020

#define MSG_SETTINGS_INVALID_BUFFER_ROWS 10000
#define MSG_SETTINGS_INVALID_BUFFER_COLUMNS 10001
#define MSG_SETTINGS_INVALID_ROWS       10002
#define MSG_SETTINGS_INVALID_COLUMNS    10003
#define MSG_SETTINGS_HOTKEY_ALREADY_ASSIGNED 10004
#define MSG_SETTINGS_DELETE_TAB         10005
#define MSG_SETTINGS_INIT_DIR           10006
#define MSG_SETTINGS_HOTKEY_NONE        10007
#define MSG_SETTINGS_FULLSCREEN_CURRENT 10008
#define MSG_ABOUT                       10009
#define MSG_SETTINGS_ICON_FILES         10010
#define MSG_SETTINGS_EXECUTABLE_FILES   10011
#define MSG_SETTINGS_EXECUTABLE_FILES_AND_LINKS 10012
#define MSG_SETTINGS_IMAGE_FILES        10013
#define MSG_SETTINGS_CONFIG_FILES       10014
#define MSG_SETTINGS_CONFIG_FILE_WRITE_ERROR 10015
#define MSG_SETTINGS_CONFIG_FILE_WRITE_ERROR_EXEDIR 10016

#define MSG_MAINFRAME_CLOSE_ALL_TABS    11000
#define MSG_MAINFRAME_CLOSE_ALL_VIEWS   11001
#define MSG_MAINFRAME_SEARCH            11002
#define MSG_MAINFRAME_EXIT_FULLSCREEN   11003
#define MSG_MAINFRAME_SYNTAX_ERROR      11004

#define MSG_TABVIEW_RUNAS               12000

#define ID_FILE_NEW_TAB                 32775
#define ID_VIEW_CONSOLE                 32777
#define ID_FILE_CLOSE_TAB               32779
#define ID_EDIT_RENAME_TAB              32781
#define ID_EDIT_SETTINGS                32783
#define ID_VIEW_MENU                    32784
#define ID_VIEW_MENU2                   32785
#define ID__EDIT                        32786
#define ID__VIEW                        32787
#define ID__HELP                        32788
#define ID_VIEW_TABS                    32789
#define ID_EDIT_CLEAR_SELECTION         32791
#define ID_EDIT_STOP_SCROLLING          32792
#define ID_VIEW_FULLSCREEN              32793
#define ID_VIEW_ZOOM_100                32794
#define ID_VIEW_ZOOM_INC                32795
#define ID_VIEW_ZOOM_DEC                32796
#define ID_FILE_CLOSE_ALL_TABS_BUT_THIS 32797
#define ID_FILE_CLOSE_ALL_TABS_LEFT     32798
#define ID_FILE_CLOSE_ALL_TABS_RIGHT    32799
#define ID_VIEW_SEARCH_BAR              32800

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        400
#define _APS_NEXT_COMMAND_VALUE         32801
#define _APS_NEXT_CONTROL_VALUE         1234
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
