//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Console.rc
//
#define IDR_POPUP_MENU_TAB              4
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDS_TAB_CREATE_FAILED           129
#define IDI_ICON1                       203
#define IDD_RENAME_TAB                  204
#define IDD_SETTINGS_MAIN               205
#define IDD_SETTINGS_CONSOLE            206
#define IDD_SETTINGS_APPEARANCE         207
#define IDD_SETTINGS_HOTKEYS            208
#define IDD_SETTINGS_TRANSPARENCY       209
#define IDD_SETTINGS_STYLES             209
#define IDD_SETTINGS_TEMP               210
#define IDD_SETTINGS_TABS               211
#define IDD_SETTINGS_BEHAVIOR           212
#define IDD_SETTINGS_TABS_1             213
#define IDD_SETTINGS_TABS_2             214
#define IDD_SETTINGS_MOUSE              215
#define IDD_CREDENTIALS                 216
#define IDC_TAB_NAME                    1000
#define IDC_APPLY                       1001
#define IDC_TREE_SECTIONS               1002
#define IDC_CHILD_PLACEHOLDER           1003
#define IDC_CHANGE_REFRESH              1005
#define IDC_REFRESH                     1006
#define IDC_ROWS                        1007
#define IDC_COLUMNS                     1008
#define IDC_BUFFER_ROWS                 1010
#define IDC_BUFFER_COLUMNS              1011
#define IDC_SHELL                       1012
#define IDC_BUFFER_ROWS2                1012
#define IDC_INIT_DIR                    1013
#define IDC_BUFFER_COLUMNS2             1013
#define IDC_BTN_BROWSE_SHELL            1015
#define IDC_BTN_BROWSE_DIR              1016
#define IDC_CLR_00                      1017
#define IDC_BTN_BROWSE_BK               1017
#define IDC_CLR_01                      1018
#define IDC_CLR_02                      1019
#define IDC_CLR_03                      1020
#define IDC_CLR_04                      1021
#define IDC_CLR_05                      1022
#define IDC_CLR_06                      1023
#define IDC_CLR_07                      1024
#define IDC_CLR_08                      1025
#define IDC_CLR_09                      1026
#define IDC_CLR_10                      1027
#define IDC_CLR_11                      1028
#define IDC_CLR_12                      1029
#define IDC_CLR_13                      1030
#define IDC_CLR_14                      1031
#define IDC_CLR_15                      1032
#define IDC_DEF_00                      1033
#define IDC_DEF_01                      1034
#define IDC_DEF_02                      1035
#define IDC_DEF_03                      1036
#define IDC_DEF_04                      1037
#define IDC_DEF_05                      1038
#define IDC_DEF_06                      1039
#define IDC_DEF_07                      1040
#define IDC_DEF_08                      1041
#define IDC_DEF_09                      1042
#define IDC_DEF_10                      1043
#define IDC_DEF_11                      1044
#define IDC_DEF_12                      1045
#define IDC_DEF_13                      1046
#define IDC_DEF_14                      1047
#define IDC_DEF_15                      1048
#define IDC_FONT                        1049
#define IDC_BTN_BROWSE_FONT             1050
#define IDC_FONT_SIZE                   1051
#define IDC_SPIN_FONT_SIZE              1052
#define IDC_CHECK_BOLD                  1053
#define IDC_CHECK_ITALIC                1054
#define IDC_ACTIVE_ALPHA                1055
#define IDC_SPIN_INSIDE_BORDER          1056
#define IDC_INACTIVE_ALPHA              1057
#define IDC_SPIN_CHANGE_REFRESH         1058
#define IDC_SPIN_REFRESH                1059
#define IDC_BTN_BROWSE_ICON             1060
#define IDC_SPIN_ROWS                   1061
#define IDC_SPIN_BUFFER_ROWS            1062
#define IDC_SPIN_COLUMNS                1063
#define IDC_SPIN_BUFFER_COLUMNS         1064
#define IDC_BTN_RESET_COLORS            1065
#define IDC_SPIN_BUFFER_ROWS2           1065
#define IDC_STATIC_ACTIVE_ALPHA         1066
#define IDC_SPIN_BUFFER_COLUMNS2        1066
#define IDC_STATIC_INACTIVE_ALPHA       1067
#define IDC_TRANSPARENCY_TYPE           1068
#define IDC_TRANSPARENCY_TYPE1          1069
#define IDC_TRANSPARENCY_TYPE2          1070
#define IDC_TRANSPARENCY_TYPE3          1071
#define IDC_KEY_COLOR                   1072
#define IDC_STATIC_ACTIVE_WINDOW        1073
#define IDC_STATIC_INACTIVE_WINDOW      1074
#define IDC_STATIC_KEY_COLOR            1075
#define IDC_LIST_HOTKEYS                1076
#define IDC_BTN_ASSIGN                  1077
#define IDC_EDIT_HOTKEY                 1078
#define IDC_EDIT_COMMAND                1079
#define IDC_KEY_COLOR2                  1079
#define IDC_SELECTION_COLOR             1079
#define IDC_BTN_CLEAR                   1080
#define IDC_FONT_COLOR                  1081
#define IDC_CHECK_USE_COLOR             1082
#define IDC_CHECK_SHOW_MENU             1083
#define IDC_CHECK_SHOW_TOOLBAR          1084
#define IDC_CHECK_SHOW_STATUS           1085
#define IDC_CHECK_SHOW_TABS             1086
#define IDC_CHECK_STYLE_CAPTION         1087
#define IDC_CHECK_STYLE_RESIZABLE       1088
#define IDC_CHECK_STYLE_TASKBAR         1089
#define IDC_CHECK_STYLE_BORDER          1090
#define IDC_INSIDE_BORDER               1091
#define IDC_POS_X                       1092
#define IDC_CHECK_HIDE_SINGLE_TAB       1092
#define IDC_CHECK_STYLE_TRAY            1093
#define IDC_POS_Y                       1094
#define IDC_CHECK_HIDE_SCROLLBARS       1094
#define IDC_CHECK_SHOW_SCROLLBARS       1094
#define IDC_RADIO_DOCK_NONE             1095
#define IDC_CHECK_SHOW_SCROLLBARS2      1095
#define IDC_CHECK_FLAT_SCROLLBARS       1095
#define IDC_RADIO_DOCK_TL               1096
#define IDC_RADIO_DOCK_TR               1097
#define IDC_RADIO_DOCK_BL               1098
#define IDC_RADIO_DOCK_BR               1099
#define IDC_RADIO_Z_REGULAR             1100
#define IDC_TRIM_TAB_TITLES             1101
#define IDC_RADIO_Z_BOTTOM              1102
#define IDC_TRIM_TAB_TITLES_RIGHT       1102
#define IDC_RADIO_Z_ONTOP               1103
#define IDC_SNAP                        1104
#define IDC_CHECK_POSITION              1105
#define IDC_CHECK_SNAP                  1106
#define IDC_SPIN_X                      1107
#define IDC_SPIN_Y                      1108
#define IDC_SPIN_SNAP                   1109
#define IDC_WINDOW_TITLE                1110
#define IDC_WINDOW_ICON                 1111
#define IDC_CHECK_USE_TAB_TITLE         1112
#define IDC_CHECK_USE_TAB_ICON          1113
#define IDC_CHECK_SHOW_COMMAND          1114
#define IDC_CHECK_SHOW_COMMAND_TABS     1115
#define IDC_LIST_TABS                   1116
#define IDC_SPIN_Y2                     1116
#define IDC_SPIN_TRIM_TAB_TITLES        1116
#define IDC_TAB_TITLE                   1117
#define IDC_SPIN_TRIM_TAB_TITLES_RIGHT  1117
#define IDC_TAB_ICON                    1118
#define IDC_RADIO_Z_DESKTOP             1118
#define IDC_TAB_SHELL                   1119
#define IDC_TAB_INIT_DIR                1120
#define IDC_COMBO_CURSOR                1121
#define IDC_CURSOR_COLOR                1122
#define IDC_RADIO_BK_TYPE               1123
#define IDC_RADIO_BK_TYPE2              1124
#define IDC_RADIO_BK_TYPE3              1125
#define IDC_BK_COLOR                    1126
#define IDC_BK_IMAGE                    1127
#define IDC_CHECK_BK_RELATIVE           1128
#define IDC_CHECK_BK_EXTEND             1129
#define IDC_COMBO_BK_POS                1130
#define IDC_TINT_COLOR                  1131
#define IDC_TINT_OPACITY                1132
#define IDC_STATIC_TINT_OPACITY         1133
#define IDC_BTN_ADD                     1134
#define IDC_BTN_UP                      1135
#define IDC_BTN_DOWN                    1136
#define IDC_BTN_DELETE                  1137
#define IDC_STATIC_BK_COLOR             1138
#define IDC_STATIC_TINT_COLOR           1139
#define IDC_STATIC_BK_IMAGE             1140
#define IDC_STATIC_BK_POS               1141
#define IDC_TINT_OPACITY_VAL            1142
#define IDC_CHECK_COPY_ON_SELECT        1143
#define IDC_CHECK_NO_WRAP               1144
#define IDC_TAB1                        1144
#define IDC_CHECK_TRIM_SPACES           1145
#define IDC_CHECK1                      1145
#define IDC_CHECK_DRAG_ON               1146
#define IDC_TABS                        1146
#define IDC_CHECK_CLEAR_ON_COPY         1146
#define IDC_CHECK_INVERSE_SHIFT         1147
#define IDC_CHECK_USE_CONSOLE_TITLE     1147
#define IDC_CHECK_SENSITIVE_COPY        1147
#define IDC_CHECK_TRIM_TAB_TITLES       1148
#define IDC_STATIC_TRIM_CHARS           1149
#define IDC_PAGE_SCROLL                 1150
#define IDC_PAGE_SCROLL2                1151
#define IDC_SCROLL_PAGE_ROWS            1152
#define IDC_SPIN_SCROLL_PAGE_ROWS       1153
#define IDC_STATIC_ROWS                 1154
#define IDC_STATIC_VERSION              1155
#define IDC_TAB_FLASHES                 1155
#define IDC_CHECK_SAVE_POSITION         1156
#define IDC_SPIN_TAB_FLASHES            1156
#define IDC_CHECK_SAVE_SIZE             1157
#define IDC_CHECK_USE_SCROLL_LOCK       1158
#define IDPANE_ROWS_COLUMNS             1159
#define IDC_LIST_MOUSE_COMMANDS         1160
#define IDC_COMBO_BUTTONS               1161
#define IDC_CHECK_CTRL                  1162
#define IDC_CHECK_SHIFT                 1163
#define IDC_CHECK_USER_DATA_DIR         1163
#define IDC_CHECK_ALT                   1164
#define IDC_RADIO_COPY_NEWLINE_CHAR     1164
#define IDC_RADIO2                      1165
#define IDC_COMBO_DOCKING               1167
#define IDC_COMBO_ZORDER                1168
#define IDC_CHECK_FLASH_TAB             1168
#define IDC_COMBO_SMOOTHING             1169
#define IDC_CHECK_LEAVE_HIGHLIGHTED     1170
#define IDC_CHECK_START_HIDDEN          1171
#define IDC_CHECK_DEFAULT_ICON          1172
#define IDC_CHECK_TABS_ON_BOTTOM        1173
#define IDC_TAB_USER                    1174
#define IDC_USER                        1175
#define IDC_PASSWORD                    1176
#define IDC_STATIC_TRIM_CHARS_RIGHT     1176
#define IDC_CHECK_RUN_AS_USER           1177
#define ID_NEW_TAB_1                    2000
#define ID_SWITCH_TAB_1                 2100
#define ID_NEXT_TAB                     2200
#define ID_PREV_TAB                     2201
#define IDC_DUMP_BUFFER                 3000
#define IDS_ERR_CANT_START_SHELL        5000
#define IDS_ERR_CANT_START_AS_USER      5001
#define IDS_ERR_CANT_START_SHELL_AS_USER 5001
#define MSG_SETTINGS_INVALID_BUFFER_ROWS 10000
#define MSG_SETTINGS_INVALID_BUFFER_COLUMNS 10001
#define MSG_SETTINGS_INVALID_ROWS       10002
#define MSG_SETTINGS_INVALID_COLUMNS    10003
#define ID_FILE_NEW_TAB                 32775
#define ID_VIEW_CONSOLE                 32777
#define ID_FILE_CLOSE_TAB               32779
#define ID_EDIT_RENAME_TAB              32781
#define ID_EDIT_SETTINGS                32783
#define ID_VIEW_MENU                    32784
#define ID__EDIT                        32786
#define ID__VIEW                        32787
#define ID__HELP                        32788
#define ID_VIEW_TABS                    32789
#define ID_EDIT_CLEAR_SELECTION         32791
#define ID_EDIT_STOPSCROLLING           32792
#define ID_EDIT_STOP_SCROLLING          32793

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        217
#define _APS_NEXT_COMMAND_VALUE         32794
#define _APS_NEXT_CONTROL_VALUE         1178
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
